grafana:
  adminPassword: admin
  defaultDashboardsEnabled: false
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
      label: grafana_dashboard
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
  service:
    type: NodePort
    nodePort: 30300
  additionalDataSources:
    - name: Loki
      type: loki
      uid: loki
      url: http://loki.loki.svc.cluster.local:3100
      access: proxy

prometheus:
  service:
    type: NodePort
    nodePort: 30090
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    retention: 6h
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    storageSpec: {}

alertmanager:
  enabled: true
  alertmanagerSpec:
    resources:
      requests:
        cpu: 25m
        memory: 64Mi

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi

kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
defaultRules:
  disabled:
    Watchdog: true
    InfoInhibitor: true 
